
$image = Pictures/Wallpapers/lena.jpeg
$background = rgba(131318ff)

$image = Pictures/Wallpapers/lena.jpeg
$error = rgba(ffb4abff)

$image = Pictures/Wallpapers/lena.jpeg
$error_container = rgba(93000aff)

$image = Pictures/Wallpapers/lena.jpeg
$inverse_on_surface = rgba(303036ff)

$image = Pictures/Wallpapers/lena.jpeg
$inverse_primary = rgba(565992ff)

$image = Pictures/Wallpapers/lena.jpeg
$inverse_surface = rgba(e4e1e9ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_background = rgba(e4e1e9ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_error = rgba(690005ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_error_container = rgba(ffdad6ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_primary = rgba(282b60ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_primary_container = rgba(e1e0ffff)

$image = Pictures/Wallpapers/lena.jpeg
$on_primary_fixed = rgba(12144bff)

$image = Pictures/Wallpapers/lena.jpeg
$on_primary_fixed_variant = rgba(3f4178ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_secondary = rgba(2e2f42ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_secondary_container = rgba(e2e0f9ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_secondary_fixed = rgba(191a2cff)

$image = Pictures/Wallpapers/lena.jpeg
$on_secondary_fixed_variant = rgba(454559ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_surface = rgba(e4e1e9ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_surface_variant = rgba(c7c5d0ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_tertiary = rgba(46263bff)

$image = Pictures/Wallpapers/lena.jpeg
$on_tertiary_container = rgba(ffd8edff)

$image = Pictures/Wallpapers/lena.jpeg
$on_tertiary_fixed = rgba(2e1125ff)

$image = Pictures/Wallpapers/lena.jpeg
$on_tertiary_fixed_variant = rgba(5f3c52ff)

$image = Pictures/Wallpapers/lena.jpeg
$outline = rgba(918f9aff)

$image = Pictures/Wallpapers/lena.jpeg
$outline_variant = rgba(46464fff)

$image = Pictures/Wallpapers/lena.jpeg
$primary = rgba(bfc1ffff)

$image = Pictures/Wallpapers/lena.jpeg
$primary_container = rgba(3f4178ff)

$image = Pictures/Wallpapers/lena.jpeg
$primary_fixed = rgba(e1e0ffff)

$image = Pictures/Wallpapers/lena.jpeg
$primary_fixed_dim = rgba(bfc1ffff)

$image = Pictures/Wallpapers/lena.jpeg
$scrim = rgba(000000ff)

$image = Pictures/Wallpapers/lena.jpeg
$secondary = rgba(c5c4ddff)

$image = Pictures/Wallpapers/lena.jpeg
$secondary_container = rgba(454559ff)

$image = Pictures/Wallpapers/lena.jpeg
$secondary_fixed = rgba(e2e0f9ff)

$image = Pictures/Wallpapers/lena.jpeg
$secondary_fixed_dim = rgba(c5c4ddff)

$image = Pictures/Wallpapers/lena.jpeg
$shadow = rgba(000000ff)

$image = Pictures/Wallpapers/lena.jpeg
$source_color = rgba(1a1c44ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface = rgba(131318ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_bright = rgba(39383fff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_container = rgba(1f1f25ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_container_high = rgba(2a292fff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_container_highest = rgba(35343aff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_container_low = rgba(1b1b21ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_container_lowest = rgba(0e0e13ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_dim = rgba(131318ff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_tint = rgba(bfc1ffff)

$image = Pictures/Wallpapers/lena.jpeg
$surface_variant = rgba(46464fff)

$image = Pictures/Wallpapers/lena.jpeg
$tertiary = rgba(e8b9d4ff)

$image = Pictures/Wallpapers/lena.jpeg
$tertiary_container = rgba(5f3c52ff)

$image = Pictures/Wallpapers/lena.jpeg
$tertiary_fixed = rgba(ffd8edff)

$image = Pictures/Wallpapers/lena.jpeg
$tertiary_fixed_dim = rgba(e8b9d4ff)

